<?php

declare(strict_types=1);

// Vorlage ohne Geheimwerte. Die echte Datei liegt ausschließlich unter
// /home/www/carmaja-private-shop/config/runtime-config.php mit Modus 0600.
return [
    'environment' => 'production',
    'publishTarget' => 'production',
    'productionPublishEnabled' => false,
    'privateDir' => '/home/www/carmaja-private-shop',
    'productPrivateDir' => '/home/www/carmaja-private-production',
    'productionPrivateDir' => '/home/www/carmaja-private-shop',
    'productionApiWebroot' => '/home/www/carmaja-production-api',
    'productionWebsiteWebroot' => '/home/www/carmaja',
    'usersFile' => '/home/www/carmaja-private-production/auth/api-users.json',
    'tokenPepper' => null,
    'githubAdapterEnabled' => false,
    'githubRepository' => 'Bumpers210/armband-rechner',
    'githubBranch' => 'main',
    'commerceDsn' => null,
    'commerceUser' => null,
    'commercePassword' => null,
    'commerceTlsCaPath' => null,
    'commerceRequireTls' => true,
    'commerceRestoreDsn' => null,
    'commerceRestoreUser' => null,
    'commerceRestorePassword' => null,
    'commerceRestoreTlsCaPath' => null,
    'commerceRestoreRequireTls' => true,
    'backupDirectory' => '/home/www/carmaja-private-shop/backups',
    'backupOffsiteTarget' => 'onedrive-pull://carmaja-production/Carmaja-Perlen/Backups',
    'backupEncryptionKeyFile' => '/home/www/carmaja-private-shop/config/backup-key.php',
    'backupEncryptionKey' => null,
    'backupEncryptionKeyId' => 'carmaja-backup-2026-08-v1',
    'stripeSecretKey' => null,
    'stripeWebhookSecret' => null,
    'stripeWebhookPayloadKey' => null,
    'stripeWebhookPayloadKeyId' => null,
    'stripeAutoload' => '/home/www/carmaja-private-shop/vendor/autoload.php',
    'stripeSdkVersion' => '20.3.0',
    'stripeApiVersion' => '2026-06-24.dahlia',
    'stripeWebhookApiVersion' => '2026-07-29.dahlia',
    'stripePaymentMethodTypes' => ['card', 'klarna', 'sepa_debit'],
    'stripeSuccessUrl' => 'https://www.carmaja-perlen.de/shop/success?session_id={CHECKOUT_SESSION_ID}',
    'stripeCancelUrl' => 'https://www.carmaja-perlen.de/shop/cancel',
    'activeLegalBundleId' => 'cmj-production-legal-2026-08-11-v4',
    'shippingMethodId' => 'deutsche-post-maxibrief',
    'shippingPublicName' => 'Deutsche Post Maxibrief',
    'shippingAmountMinor' => 270,
    'shippingMinBusinessDays' => 2,
    'shippingMaxBusinessDays' => 4,
    'shopWebsiteOrigin' => 'https://www.carmaja-perlen.de',
    'brevoApiKey' => null,
    'brevoSenderEmail' => null,
    'brevoSenderName' => 'Carmaja-Perlen Shop',
    // Erst nach geprüftem Alarmtest kontrolliert auf true setzen.
    'monitorEnabled' => false,
    'monitorAlertEmail' => null,
];
