<?php

declare(strict_types=1);

// Vorlage ohne Geheimwerte. Die echte Datei liegt ausschließlich unter
// /home/www/carmaja-private-shop/config/runtime-config.php mit Modus 0600.
return [
    'environment' => 'production',
    'publishTarget' => 'production',
    'productionPublishEnabled' => false,
    'privateDir' => '/home/www/carmaja-private-shop',
    'testPrivateDir' => '/home/www/carmaja-private-test',
    'testApiWebroot' => '/home/www/carmaja-test-api',
    'testWebsiteWebroot' => '/home/www/carmaja-test-site',
    'productionPrivateDir' => '/home/www/carmaja-private-shop',
    'productionApiWebroot' => '/home/www/carmaja-shop-api',
    'productionWebsiteWebroot' => '/home/www/carmaja-site',
    'usersFile' => '/home/www/carmaja-private-shop/auth/api-users.json',
    'tokenPepper' => null,
    'githubAdapterEnabled' => false,
    'githubRepository' => 'Bumpers210/armband-rechner',
    'githubBranch' => 'main',
    'githubTokenFile' => null,
    'commerceDsn' => null,
    'commerceUser' => null,
    'commercePassword' => null,
    'commerceTlsCaPath' => null,
    'commerceRequireTls' => true,
    'stripeSecretKey' => null,
    'stripeWebhookSecret' => null,
    'stripeWebhookPayloadKey' => null,
    'stripeWebhookPayloadKeyId' => null,
    'stripeAutoload' => '/home/www/carmaja-private-shop/vendor/autoload.php',
    'stripeSdkVersion' => '20.3.0',
    'stripeApiVersion' => '2026-06-24.dahlia',
    'stripeWebhookApiVersion' => '2026-07-29.dahlia',
    'stripePaymentMethodTypes' => ['card', 'paypal', 'klarna', 'sepa_debit'],
    'stripeSuccessUrl' => 'https://www.carmaja-perlen.de/shop/success?session_id={CHECKOUT_SESSION_ID}',
    'stripeCancelUrl' => 'https://www.carmaja-perlen.de/shop/cancel',
    'activeLegalBundleId' => 'cmj-production-legal-2026-08-07-v3',
    'shippingMethodId' => 'deutsche-post-maxibrief',
    'shippingPublicName' => 'Deutsche Post Maxibrief',
    'shippingAmountMinor' => 270,
    'shippingMinBusinessDays' => 2,
    'shippingMaxBusinessDays' => 4,
    'shopWebsiteOrigin' => 'https://www.carmaja-perlen.de',
    'brevoApiKey' => null,
    'brevoSenderEmail' => null,
    'brevoSenderName' => 'Carmaja-Perlen Shop',
];
